name: Node CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Checkout Code
      uses: actions/checkout@master

    - name: Install & Build
      run: |
        npm install
        npm run generate


    - name: Deploy Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: docs
        fqdn: npmer.woolson.cn
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
